### ISSUE TITLE
wrong elf class elfclass64

### ISSUE THREAD

**Issue by promentol** [saghul/node-abstractsocket#20]
I am building on Ubuntu 64 bit, for Raspberry armv7l architecture.

The package is throwing following error "wrong elf class elfclass64"

any ideas how to fix this?

**Comment by saghul** [comment]
Oh, never seen that one before. Can you paste the build output?

**Comment by namxam** [comment]
I am getting this on a raspberry pi 4

```bash

> abstract-socket@2.1.1 install /home/pi/node_modules/abstract-socket
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/bindings/src/abstract_socket.o
In file included from ../src/abstract_socket.cc:5:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2294:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:5:
../src/abstract_socket.cc: At global scope:
/home/pi/.cache/node-gyp/14.9.0/include/node/node.h:746:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/14.9.0/include/node/node.h:780:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/abstract_socket.cc:181:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(abstract_socket, Initialize)
 ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/home/pi/node_modules/abstract-socket/build'

> abstract-socket@1.1.0 install /home/pi/node_modules/omxplayer-dbus/node_modules/abstract-socket
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/omxplayer-dbus/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/abstract_socket/src/abstract_socket.o
In file included from ../src/abstract_socket.cc:9:
../../../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../../../nan/nan.h:2294:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/abstract_socket.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Bind(Nan::NAN_METHOD_ARGS_TYPE)':
../src/abstract_socket.cc:98:30: error: no matching function for call to 'v8::Value::Int32Value()'
     fd = info[0]->Int32Value();
                              ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note: candidate: 'v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc:99:35: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)'
     String::Utf8Value path(info[1]);
                                   ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:3287:5: note: candidate: 'v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)'
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:3287:5: note:   candidate expects 2 arguments, 1 provided
../src/abstract_socket.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Connect(Nan::NAN_METHOD_ARGS_TYPE)':
../src/abstract_socket.cc:136:30: error: no matching function for call to 'v8::Value::Int32Value()'
     fd = info[0]->Int32Value();
                              ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note: candidate: 'v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc:137:35: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)'
     String::Utf8Value path(info[1]);
                                   ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:3287:5: note: candidate: 'v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)'
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:3287:5: note:   candidate expects 2 arguments, 1 provided
../src/abstract_socket.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Close(Nan::NAN_METHOD_ARGS_TYPE)':
../src/abstract_socket.cc:170:30: error: no matching function for call to 'v8::Value::Int32Value()'
     fd = info[0]->Int32Value();
                              ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note: candidate: 'v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:2869:40: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc: In function 'void {anonymous}::Initialize(v8::Local<v8::Object>)':
../src/abstract_socket.cc:203:65: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
                 Nan::New<FunctionTemplate>(Socket)->GetFunction());
                                                                 ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc:205:63: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
                 Nan::New<FunctionTemplate>(Bind)->GetFunction());
                                                               ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc:207:66: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
                 Nan::New<FunctionTemplate>(Connect)->GetFunction());
                                                                  ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/abstract_socket.cc:209:64: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
                 Nan::New<FunctionTemplate>(Close)->GetFunction());
                                                                ^
In file included from /home/pi/.cache/node-gyp/14.9.0/include/node/node.h:67,
                 from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note: candidate: 'v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)'
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/pi/.cache/node-gyp/14.9.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
In file included from ../../../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:9:
../src/abstract_socket.cc: At global scope:
/home/pi/.cache/node-gyp/14.9.0/include/node/node.h:746:43: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/14.9.0/include/node/node.h:780:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/abstract_socket.cc:215:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(abstract_socket, Initialize)
 ^~~~~~~~~~~
make: *** [abstract_socket.target.mk:109: Release/obj.target/abstract_socket/src/abstract_socket.o] Error 1
make: Leaving directory '/home/pi/node_modules/omxplayer-dbus/node_modules/abstract-socket/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/omxplayer-dbus/node_modules/abstract-socket
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN media-player@1.0.0 No description
npm WARN media-player@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@1.1.0 (node_modules/omxplayer-dbus/node_modules/abstract-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ abstract-socket@2.1.1
updated 1 package and audited 116 packages in 11.222s

2 packages are looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
